plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {}

        server {
            args '--nogui'
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    maven {
        url 'https://maven.architectury.dev/'
    }
    maven {
        url 'https://maven.latvian.dev/releases'
    }
    maven {
        url 'https://cursemaven.com'
    }
    maven {
        url 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    compileOnly fg.deobf('curse.maven:jade-324717:6271651')
    compileOnly fg.deobf('maven.modrinth:5sy6g3kz:rnhiaw3t')
    compileOnly fg.deobf('dev.latvian.mods:kubejs-forge:2001.6.5-build.16')
    compileOnly fg.deobf('dev.latvian.mods:rhino-forge:2001.2.2-build.17')
    if ((findProperty('enable_kubejs_dev') ?: 'false').toBoolean()) {
        runtimeOnly fg.deobf('dev.latvian.mods:kubejs-forge:2001.6.5-build.16')
        runtimeOnly fg.deobf('dev.architectury:architectury-forge:9.1.12')
        runtimeOnly fg.deobf('dev.latvian.mods:rhino-forge:2001.2.2-build.17')
    }
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest.attributes('Implementation-Version': project.version)
    finalizedBy 'reobfJar'
}
